//import './01-variables'
//import './02-operadores'
//import './03-condicionales'
//import './04-ciclos'
//import './05-funciones'
//import './06-arreglos-&-objetos'
// import './homework/todo'
// import './homework/fizzbuzz'
//import "./homework/Arreglos-Estudiantes"
//import './homework/fibonachi'
//import './homework/sudoku'
import './homework/numerosPrimos'